### ISSUE TITLE
Fills = c(...) doesnt work anymore

### ISSUE THREAD

**Issue by SebastianHesse** [jolars/eulerr#51] opened 2019-06-06 11:57 UTC
Hi,
in my script that I used to draw VENN diagrams I used the following to color the plot:
`VENN_all <- plot(venn(vsHD_reg_0.05[, 3:6]), 
     edges = T,
     quantities = T,
     fills = c("#377eb8", "#4daf4a", "#984ea3", "#ff7f00"))`

Unfortunately this doesn't have an effect anymore and no colors are printed anymore. Also, I noticed that the shape of the VENN diagram changed a bit with emphasis on the parts without overlap. 
Is this a bug or is there a way to fix it?

Thank you!
Sebastian

**Comment by jolars** [comment] 2019-06-06 17:05
Could you please provide a reproducible example? Tell me what you expect.

Anyway, what I think is going on is that you are now using a newer version of eulerr than before. With version 4.0.0, the mechanism for color fills changed. Instead of using opacity values and overlaying shapes on top of each other, the package is now splitting the shapes into individual polygons and filling overlaps by mixing colors. If you want this, default, behavior, you simply input one color for each shape. If you want complete control, you can add additional colors which will be used to fill all the overlaps.

**Comment by jolars** [comment] 2019-07-03 16:36
I'm closing this now because I don't understand what's wrong. Please reopen if you have more information to provide.

**Closed by jolars** 2019-07-03 16:36 UTC
